ping[google]: ping 8.8.8.8
ping[cloudflare]: ping 1.1.1.1
time: while true; do date; sleep 1; done
echo[hello]: echo Hello, world!
echo[good-by]: echo Good-bye world!
boolean[true]: true
boolean[false]: false
256-color: curl -s https://gist.githubusercontent.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263/raw/e50a28ec54188d2413518788de6c6367ffcea4f7/print256colours.sh | bash
README: cat README.md
env: env