name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    name: Test `cargo check/test` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - run: |
        rustup set auto-self-update disable
        rustup toolchain install stable --profile minimal
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.2.0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        cargo check --verbose
        cargo test --verbose
